### PR TITLE
CB-9538 - Implementing FadeSplashScreen for Android

### PR DESCRIPTION
**Pull request by trancee**
FadeSplashScreen is supported by using AlphaAnimation to fade out the ImageView.

### CODE REVIEW

**Comment by spiritax** [comment]
Thanks for the code.

The property FadeSplashScreenDuration (float, defaults to 2): is a float, so you should probably read a Double then cast it on Integer.

final int splashscreenDuration = (int)(preferences.getDouble("FadeSplashScreenDuration", 2) * 1000);

**Comment by purplecabbage** [comment]
Other time values are given in msecs. You should be consistent.

**Comment by trancee** [comment]
I am just being compatible to the already existing preference which is given in seconds (coming from iOS).

**Comment by purplecabbage** [comment]
SplashScreenDelay (number, default to 10000). Amount of time in milliseconds to wait before automatically hide splash screen.

**Comment by trancee** [comment]
I agree with your point, but due to the already implemented FadeSplashScreenDuration (splash-screen Fade duration in seconds) I can not simply change the documented behavior. It would be incompatible with the iOS platform.

**Comment by idpaterson** [comment]
Thanks, this works well! Can you follow through with the [recommended contributor workflow](http://cordova.apache.org/#contribute) then update this pull request to match the corresponding issue that you create in [Jira](https://issues.apache.org/jira/) to make sure this fix is seen by the correct people?

**Comment by daserge** [comment]
@trancee, could you please update this to be consistent with the current documented format [`FadeSplashScreenDuration (float, defaults to 3000)`](https://github.com/apache/cordova-plugin-splashscreen#ios-quirks) on iOS?

A fallback can be also added to handle seconds-values for backwards-compatibility:
https://github.com/apache/cordova-plugin-splashscreen/blob/ccb3c2f4533fa52da474c33a7adc5ab5a887a805/src/ios/CDVSplashScreen.m#L346-L351

**Comment by daserge** [comment]
@trancee, I've updated this PR in #73 - please take a look.

**Comment by daserge** [comment]
@trancee, could you please close this?
#73 has been merged.

**Comment by trancee** [comment]
Sure. Thanks for the merge.

**Pull request closed without merging**
