### PR TITLE
feat(android): add support for splash screen theme and background color

### PR DESCRIPTION
**Pull request by janpio**
This is based on https://github.com/apache/cordova-plugin-splashscreen/pull/161 by @IndieSW. 

Per the user's description their changes were done on 4.0.x, so I took their file and created a PR for it in the 4.0.x branch. 

Diff looks much better.

👊 This is _not_ to be merged, but use as a template for a new PR for `master`.

### CODE REVIEW

**Comment by IndieSW** [comment]
@janpio Well done!

**Comment by BorntraegerMarc** [comment]
is the AppVeyor build failing because of these changes or is it failing generally everywhere?

**Comment by BorntraegerMarc** [comment]
actually it seems to succeed on master: https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-plugin-splashscreen

**Comment by janpio** [comment]
@BorntraegerMarc 4.0.0 probably was not configured for AppVeyor yet, meaning it has no configuration here to run and falls back to a default that does not work with the code.

**Comment by IndieSW** [comment]
This was used to set the splash dialog theme to the app theme and provided for a seamless transition (no screen flashes) from splash to app.

**Comment by janpio** [comment]
Yep, use it clear and good - so I hope some day someone has enough time to recreate this PR for `master` so it can be merged.

**Pull request closed without merging**
