### PR TITLE
Add dots spinner loader for android

### PR DESCRIPTION
**Pull request by airstep**
### Platforms affected
Android

### What does this PR do?
Show dots animation in spinner

### What testing has been done on this change?
on android 6.0.1

### CODE REVIEW

**Comment by janpio** [comment]
Hey, I just fixed the problem that caused Android tests to fail in `master`. Could you rebase this PR please? This should get rid of the Android failures and possibly fix all test failures for this PR.

**Comment by airstep** [comment]
What you mean about rebase? How to do it?

**Comment by janpio** [comment]
`rebase` is git command that takes your changes from your branch, which was created in the past and with an old state of code, and moves it to present to the current code. Your changes stay here, but you get all the changes that happened in between. In this case, this would mean the fixes for the tests.

Here are 2 tutorials:
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
https://stackoverflow.com/a/46148801/252627

Looks pretty complicated, but is _very_ simple if you understood it (and you don't have any merge conflict - but your change won't).

**Comment by janpio** [comment]
Closing and re-opening to trigger a new CI/test run with new PR merge.

**Pull request closed without merging**
