### PR TITLE
Update CDVSplashScreen.m and CDVSplashScreen.h

### PR DESCRIPTION
**Pull request by Reneoh**
Added support for iPhone X with legacy method. Usefull when you don't want to use a LaunchStoryboard.

### CODE REVIEW

**Comment by Reneoh** [comment]
also added a bool for iPhoneX in CDVSplashScreen.h

**Comment by nadavmos** [comment]
.. and you are also missing the asset catalog version prefix for iphoneX, see below:  

// Add Asset Catalog specific prefixes
    if ([imageName isEqualToString:@"LaunchImage"])
    {
        if (device.iPhone4 || device.iPhone5 || device.iPad) {
            imageName = [imageName stringByAppendingString:@"-700"];
        } else if(device.iPhone6) {
            imageName = [imageName stringByAppendingString:@"-800"];
        } else if(device.iPhone6Plus) {
            imageName = [imageName stringByAppendingString:@"-800"];
            if (currentOrientation == UIInterfaceOrientationPortrait || currentOrientation == UIInterfaceOrientationPortraitUpsideDown)
            {
                imageName = [imageName stringByAppendingString:@"-Portrait"];
            }
        **} else if(device.iPhoneX) {
             imageName = [imageName stringByAppendingString:@"-1100"];
        }**
    }

**Comment by Reneoh** [comment]
Thanks, missed that one...!

**Comment by jcesarmobile** [comment]
Closing in favour of https://github.com/apache/cordova-plugin-splashscreen/pull/146

**Pull request closed without merging**
