### PR TITLE
CB-11602: (android) Fix bug AutoHideSplashScreen false - not working

### PR DESCRIPTION
**Pull request by nbabanov**
### Platforms affected

Android
### What does this PR do?

Fixes https://issues.apache.org/jira/browse/CB-11602
### What testing has been done on this change?

Manual QA
### Checklist
- [x] [ICLA](http://www.apache.org/licenses/icla.txt) has been signed and submitted to secretary@apache.org.
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-11602: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-splashscreen/pull/109/commits/a0836cbccf5842510c3e433c03b6e6c706f42c85)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/21//PLATFORM=android/artifact/) |

**Comment by vladimir-kotikov** [comment]
@daserge, could you please review this?

**Comment by dcousens** [comment]
ping? was this fixed?

**Comment by nbabanov** [comment]
@dcousens Sadly it is still not merged in the official code base. :(

**Comment by daserge** [comment]
@nbabanov thanks for the contribution and sorry it took so long to review this.

Could you please describe your scenario - I could not reproduce the issue with latest cordova-android and master version of crosswalk-webview (splash gets hidden when I press Home or Power button with or without this change).
How do you get the activity to be paused?

As an alternative I can suggest to listen to onRestart event and restore the previous splash screen state - I would be grateful if you could test whether this works for you:
https://github.com/daserge/cordova-android/tree/CB-11602
https://github.com/daserge/cordova-plugin-splashscreen/tree/CB-11602

**Comment by daserge** [comment]
@jcesarmobile, @infil00p, @kerrishotts could you please also take a look if you have a chance?

**Comment by alanhg** [comment]
if AutoHideSplashScreen works for android.
how to use if i want to hide splashscreen manually

**Comment by filmaj** [comment]
See the relevant [dev mailing list discussion about integrating splashscreen into the platforms](https://lists.apache.org/thread.html/d94c0fe4bcec06ac45f1cc37978b713464faecbf7b938560cd6368e5@%3Cdev.cordova.apache.org%3E).

**Pull request closed without merging**
