### PR TITLE
Update CDVSplashScreen.h

### PR DESCRIPTION
**Pull request by Reneoh**
Added a BOOL for iPhoneX

### CODE REVIEW

**Comment by shazron** [comment]
This patch exists in a vacuum - what issue is this supposed to solve? Can you clarify. Thanks.
Follow the template that was presented when you started the pull request: https://github.com/apache/cordova-plugin-splashscreen/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Reneoh** [comment]
I'm totally new on github. I've made some changes to the splashscreen.m and .h files to support the iphone x screen. Sorry for messing things up here at github...

**Comment by shazron** [comment]
Saw the other PR. The other one is dependent on this one -- both should be in one PR. Also follow the PR Template.

**Comment by Reneoh** [comment]
I know, I don't know how to put changes on two files in one pull request... sorry... looking into it now.

**Comment by jcesarmobile** [comment]
Closed in favour of https://github.com/apache/cordova-plugin-splashscreen/pull/146

**Pull request closed without merging**
