### PR TITLE
On Android 7 not work 

### PR DESCRIPTION
**Pull request by caereservices**
On Android 7 the plugin seems to ignore <preference> tag in config.xml ... on Android <= 6 it works correctly.

Cordova 7.0.2
Plugin 4.0.4-dev

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Hi.
You have created a Pull Request. Can you close it?

If you want to report a bug, you can do it on issues.cordova.io

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-splashscreen/pull/126/commits/3bd0f289d726a2bc950ad58c6f106908748d399f)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/49/)

 18 tests run, 0 skipped, 0 failed.

**Comment by filmaj** [comment]
FYI @jcesarmobile I usually close these kinds of fake PRs via:

```
git commit --allow-empty -m 'Close #126'
```

.. and pushing back up to master. Only way we can do it until Apache gives us more control over GitHub :/

**Comment by jcesarmobile** [comment]
@filmaj I know, I've done it a few times, but I like to wait a few days because if the user closes it, we have less empty commits

**Pull request closed without merging**
