### PR TITLE
CB-12626: (android) Fix crash on Samsung devices and splash screen not showing on some other devices

### PR DESCRIPTION
**Pull request by Lazza**
### Platforms affected

Android, all versions.

### What does this PR do?

This PR drops the strategy of relying on the app preferences to store the `drawableId` for the splash screen. This approach causes crashes on Samsung devices and prevents the splash screen from working correctly on some other devices.

### What testing has been done on this change?

This change has been tested on all devices reported in the JIRA issue:

- Samsung Galaxy 7 Edge, Android 7.0
- Samsung Galaxy Note 4, Android 6.0.1
- Lenovo/Zuk Z1, Android 5.1.1
- Official Android Emulator with Nexus S simulated hardware, API 25

### Checklist

- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-splashscreen/pull/125/commits/f6aab146a45e172151fe931436534ba143238ec5)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=windows-10-store/artifact/) |
| [iOS 9.3]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-9.3/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-9.3/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-9.3/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-9.3/artifact/) |
| [iOS 10.0]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-10.0/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-10.0/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-10.0/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=ios-10.0/artifact/) |
| [Android 4.4]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-4.4/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-4.4/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-4.4/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-4.4/artifact/) |
| [Android 5.1]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-5.1/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-5.1/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-5.1/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/46//PLATFORM=android-5.1/artifact/) |

**Comment by Lazza** [comment]
> Cordova CI Build has one or more failures

This doesn't make sense. The build log states that the failure is on the Windows build. This PR **does not make any modification to the Windows part** of the plug-in.

**Comment by alsorokin** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-splashscreen/pull/125/commits/f6aab146a45e172151fe931436534ba143238ec5)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=windows-10-store/artifact/) |
| [iOS 9.3]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-9.3/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-9.3/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-9.3/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-9.3/artifact/) |
| [iOS 10.0]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-10.0/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-10.0/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-10.0/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=ios-10.0/artifact/) |
| [Android 4.4]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-4.4/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-4.4/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-4.4/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-4.4/artifact/) |
| [Android 5.1]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-5.1/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-5.1/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-5.1/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-splashscreen-pr/47//PLATFORM=android-5.1/artifact/) |

**Comment by Lazza** [comment]
@alsorokin, sure, go ahead. :)

**Comment by alsorokin** [comment]
@Lazza I was just restarting the tests :) As you can see, they are green now.

**Comment by Lazza** [comment]
Great! Thank you.

**Comment by filmaj** [comment]
Ping @infil00p for a review.

@Lazza have you signed an ICLA for Apache?

**Comment by Lazza** [comment]
@filmaj I don't think I have. Why?

**Comment by filmaj** [comment]
@Lazza nevermind, it is not completely required. Issuing a PR is enough to establish "intent to contribute" which is all Apache legal requires.

**Comment by filmaj** [comment]
One more question: how would one go about reproducing the crash that this patch fixes? What device did you see the crash on?

**Comment by Lazza** [comment]
@filmaj I see. 😄  Just to be clear, my PR is released under the Apache Version 2.0 license as anything else in this repo (it is also the license mentioned in the project and the file header). I am not transferring copyright to someone else that could decide to prevent my code from being under the Apache License, but I am contributing the code giving all the rights specified in the license.

Regarding the devices, I suggest to try those written in the first message above, especially the Samsung ones because they exhibited the crashes consistently and repeatably.

**Comment by filmaj** [comment]
O nice, there is an emulator in there. OK, I will try to reproduce. Thank you!

**Comment by Lazza** [comment]
Yeah, but unfortunately... I am not even sure how I got that one to crash! 😅  Most of my tests in the emulators where either working or simply not showing the splash (but not crashing). If you want to be sure about getting a crash, it's better to try a Samsung device if you can get your hands on one. 😄

**Comment by filmaj** [comment]
I think I have a Samsung S5 that I can play with.

**Comment by filmaj** [comment]
Hmm, I cannot seem to reproduce the error with the latest master of cordova-android + cordova-plugin-splashscreen.

I'm using a ~200kb .png file as a splash screen. Here's the relevant bit in my `config.xml`:

```
    <platform name="android">
        <allow-intent href="market:*" />
        <splash src="splash/splash.png" />
    </platform>
```

I've tried on an API 25 emulator using the Google APIs x86_64 image using the Nexus S device profile. I've also tried on a Samsung Galaxy S5 running Android 6.0.1.

@Lazza any other tips you can give me in trying to reproduce this? Anything in my set up above you think I need to change?

**Comment by infil00p** [comment]
@Lazza Which Samsung Devices would have this problem? Would a Samsung Galaxy S3 to S8 have this?

**Comment by SamDelgado** [comment]
I have a Samung Galaxy S7 Edge that experienced an immediate crash when my app launched. This pull request fixed it.

**Comment by Lazza** [comment]
@filmaj, @infil00p unfortunately I do not have access to many Samsung devices. I was able to test this plug-in only with the models mentioned in the PR.

As @SamDelgado confirmed, I think the best bet is to test on a Samsung Galaxy S7 Edge.

**Comment by vegetablesalad** [comment]
I can attest to this bug. Splash screen didn't show up on 5 of my test phones. Applying this resolved the issue.

**Comment by filmaj** [comment]
@vegetablesalad which devices exhibited the behaviour of splash screen not showing up? Brand and model names/numbers, along with Android operating system versions running on them, would be super helpful.

**Comment by karlachavez** [comment]
We can reproduce this issue on a Samsung S6 with the following tech specs:
http://www.samsung.com/ca/business/business-products/smartphones/smartphones/SM-G920WZWABMC

Due to it, we have to remove the splashscreen of our app.

It's important to mention that the issue is presents since the device was updated from Android 6 to Android 7. 

Do someone know when the fix proposed is going to be applied?

**Comment by Lazza** [comment]
@karlachavez 

> we have to remove the splashscreen of our app

In the meantime:

    cordova plugins remove cordova-plugin-splashscreen
    cordova plugins add https://github.com/Lazza/cordova-plugin-splashscreen#bulletproof-fix --save

**Comment by Lazza** [comment]
Are there any news on this?

**Comment by karlachavez** [comment]
Your suggest works fine. The splashscreen is not displayed on the device we had the problem, but on the rest of devices. We are going to take this workaround until an official fix is released.
Thank so much!

**Comment by uj** [comment]
Will this fix be added to the official apache version?  I can confirm that cordova-plugin-splashscreen crashes Morotola X Gen 3, Android 6, not just Samsung devices.

**Comment by Lazza** [comment]
@uj does my fix work on that device as well?

**Comment by uj** [comment]
@Lazza Ok, i just tried your fix, and it crashes less often, but not 100% crash-free.  However, this mostly happens when using the back-button to "exit" the program.  There is a separate Android bug on some devices where exiting with the back button causes the app to relaunch instead of sleep/resume even though the app is still running, and that *might* be part of the crashing problem, I don't know.  Note that when I do not use either of the splashscreen plugins at all, it NEVER crashes no matter what.

**Comment by infil00p** [comment]
Again, this PR has to do what it says it does.  The last two commits are for iOS.  @Lazza, is this on a branch for the commit, or is this on your master? If it's the latter, can you create a branch that just has the commit and issue a new PR? The iOS code in here is preventing us from accepting this PR as it is.

**Comment by Lazza** [comment]
@infil00p When I created this pull request I only added code for Android. I have **never** included iOS code at the time of creation of this pull request.

I have no idea why now GitHub has decided to include some other unrelated code into my pull request, nor I have time to investigate now. I am working on a client project and needed to have another fix as well, but of course this has been applied months after the previous pull request so it is ridiculous that it is being included here by GitHub.

As a matter of fact, my pull request code was also correctly tagged (the tag is `bulletproof-fix`).

As a side note, I see there was no intention at all to accept it even before this incident, but no big deal. People who want a correct behavior on Samsung devices can find the code.

**Comment by Lazza** [comment]
Apparently, I've been able to undo everything so it's good again now.

**Comment by infil00p** [comment]
OK, it's in.  Thanks for contributing.

**Pull request closed without merging**
