### PR TITLE
Get AutoHideSplashScreen from config.xml

### PR DESCRIPTION
**Pull request by neo-clon**
Get AutoHideSplashScreen from config.xml to manipulate when should be hide the splashscreen

### CODE REVIEW

**Comment by patcon** [comment]
:+1

If I understand correctly, the param in config.xml currently does nothing, which is unexpected...?

**Comment by neo-clon** [comment]
Yes,  currently does nothing on android, but IOS add it allows you to control when closing the splashscreen

**Comment by Bnaya** [comment]
+1 for this

**Comment by daserge** [comment]
@neo-clon, thanks for your contribution!
This has been included into #74, could you please close the PR?

**Comment by neo-clon** [comment]
Thanks,

**Pull request closed without merging**
