### PR TITLE
CB-11156 Change default FadeSplashScreenDuration value

### PR DESCRIPTION
**Pull request by daserge**
Updated the docs

[Jira issue](https://issues.apache.org/jira/browse/CB-11156)

### CODE REVIEW

**Comment by nikhilkh** [comment]
I'm assuming the default for Windows is already 500?

**Comment by nikhilkh** [comment]
LGTM.

**Comment by daserge** [comment]
Defaults for windows is being changed in https://github.com/apache/cordova-windows/pull/170.

**Comment by RobPosener** [comment]
I played around with this and found 1300 "looked the nicest".
Also, you need to update the splashscreen plugin documentation to whatever the new value is.

**Pull request merged**
