### PR TITLE
Fixed installation instructions

### PR DESCRIPTION
**Pull request by gtczap**
Current instructions yield an error in NPM:

cordova plugin add cordova-plugin-splashscreen
Fetching plugin "cordova-plugin-splashscreen" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-splashscreen
npm http 404 http://registry.cordova.io/cordova-plugin-splashscreen
Error: 404 Not Found: cordova-plugin-splashscreen
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

### CODE REVIEW

**Comment by agrieve** [comment]
The next version of the plugin will be installable by this name, it's just not working yet.

**Comment by BrunoMarchesson** [comment]
Well, 3 weeks after, still not working ?!
What are we supposed to do to add this plugin since the official instruction does not work ?

**Comment by shazron** [comment]
Just use the old org.apache.cordova.splashscreen name for now, that will work even within the deprecation period (6 months long).

**Comment by purplecabbage** [comment]
I have added specific text to the readme if you need to install this plugin directly from this repo.
9575c92db6e3efe31ca5517f4dd9405b03ebdffe
Please close this pull request.

**Comment by daserge** [comment]
Ping @gtczap, could you please close this PR?

**Pull request closed without merging**
