### PR TITLE
Fixes #235: update homepage to github readme page

### LINKED ISSUE #235: Update link to readme.md file in npm update output
please fix link to readme.md like in  cordova-plugin-file
image

what I do:
```
npm-check -u -E
```

Link should be `https://github.com/apache/cordova-plugin-splashscreen#readme` instead of `https://cordova.apache.org/`

### PR DESCRIPTION
**Pull request by blackwolf12333**
### Motivation and Context

Fixes #235 

Change was requested in issue #235

### CODE REVIEW

**Comment by breautek** [comment]
Please update the Motivation & Context so it contains the keywords "Fixes #235"

e.g.

Motivation and Context
Fixes #235 

Change was requested in issue #235

This will help github recognise that once this PR is merged, it will close #235 for automatically.

**Comment by blackwolf12333** [comment]
Oh doesn't that work when you have that in the title of the PR anymore?

**Comment by breautek** [comment]
> Oh doesn't that work when you have that in the title of the PR anymore?

Oh sorry you're actually right. I was looking for text on #235 that said that but looks like they moved it to an "i" icon.

**Comment by breautek** [comment]
I'm kinda a new member so I don't know what is acceptable for the number of reviewers required, even if the changes are trivial.

@janpio ?

**Comment by breautek** [comment]
Closing/openning to restart travis/appveyor. I believe the error checks were simply caused by a timeout.

**Pull request merged**
